### ISSUE TITLE
Please add update 6 support

### ISSUE THREAD

**Issue by Roaders** [TobbyTheBobby/TimberbornMods#18]
Sorry if this comes across as nagging! I am sure that update 6 support was on it's way but I thought I'd add an issue.

Now that we have sluice gate support in teh main game the Higher flood gates mod is no longer required. Othet that that ladder and vertical power shafts are the only must have mods and I can't play the game without!! 

THank you very much for these contributions. They make the game so much better.

**Comment by TobbyTheBobby** [comment]
Thank you for your kind words! <3

Have updated both ladder and VPS, therefore closing this issues. Other mods are still WIP but werent mentioned in this issues.

**Comment by babs** [comment]
THANKS!

**Comment by Roaders** [comment]
If you could also update the simple triggers mod that would be GREAT!!!!


joking obviously. Pretty sure they are nothing to do with you 😁
