### ISSUE TITLE
Game crashes when attempting to load save

### ISSUE THREAD

**Issue by Crowfooted** [TobbyTheBobby/TimberbornMods#23]
"Could not set up parent class"

Full exception: 

v0.6.9.2-8993f96-sw
TypeLoadException: Could not set up parent class, due to: Invalid generic instantiation assembly:data-0000028EB176E420 type:BaseBuilder`2 member:(null)
ChooChoo.TrainYardUI.TrainYardPanel`1[TBuilder].InitializeRoot () (at <f67de02b9b8b42699ef3d8401296b2b7>:0)
TimberApi.UIBuilderSystem.BaseBuilder`1[TElement].Initialize () (at <8825e448f291416fb779f5e1841880c9>:0)
TimberApi.UIBuilderSystem.UIBuilder.Create (System.Type builderType) (at <8825e448f291416fb779f5e1841880c9>:0)
TimberApi.UIBuilderSystem.UIBuilder.Create[TBuilder] () (at <8825e448f291416fb779f5e1841880c9>:0)
ChooChoo.TrainYardUI.TrainYardFragment.InitializeFragment () (at <f67de02b9b8b42699ef3d8401296b2b7>:0)
Timberborn.EntityPanelSystem.EntityPanel.AddFragments (System.Collections.Generic.IEnumerable`1[T] fragments, UnityEngine.UIElements.VisualElement parent) (at <b3dc07ae6c214becbded54a68cc09f5b>:0)
Timberborn.EntityPanelSystem.EntityPanel.InitializeModules () (at <b3dc07ae6c214becbded54a68cc09f5b>:0)
Timberborn.EntityPanelSystem.EntityPanel.Load () (at <b3dc07ae6c214becbded54a68cc09f5b>:0)
(wrapper dynamic-method) Timberborn.SingletonSystem.SingletonLifecycleService.DMD<Timberborn.SingletonSystem.SingletonLifecycleService::LoadSingletons>(Timberborn.SingletonSystem.SingletonLifecycleService)
(wrapper dynamic-method) Timberborn.SingletonSystem.SingletonLifecycleService.DMD<Timberborn.SingletonSystem.SingletonLifecycleService::LoadAll>(Timberborn.SingletonSystem.SingletonLifecycleService)
Timberborn.SingletonSystem.SingletonLifecycleAdapter.Start () (at <83c35e71bcfd4e238b263c72f0ec19cd>:0)

**Comment by TobbyTheBobby** [comment]
This error means either an older version of ChooChoo or TimberAPI. This issue has already been fixed, but not yet pushed to github. Make sure to update the mod and TimberAPI to latest version.
